### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by beatnickgr** [arnaucode/commonroutesServer#9]
Tapping a user's telegram link would be expected to open the contact in telegram.

**Comment by beatnickgr** [comment]
It's working already. I did wrong testing.

**Comment by arnaucode** [comment]
Well, the issue is correct. In the current version, it works in the telegram button at the user profile, but it don't works in telegram button of the travel view. In the dev version (the actual code in this repository) this is fixed and it works.
Thanks for the feedback
